name: anime-watcher

services:
  anime-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime-watcher
    user: "0:0"
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./data:/app/data
